/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author harshithachennareddy
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem ecosystem;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        createNewEnterpriseJButton = new javax.swing.JButton();
        createNewEnterpriseAdminJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(237, 252, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sathu", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        createNewEnterpriseJButton.setBackground(new java.awt.Color(231, 244, 255));
        createNewEnterpriseJButton.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        createNewEnterpriseJButton.setText("Create New Enterprise");
        createNewEnterpriseJButton.setPreferredSize(new java.awt.Dimension(136, 23));
        createNewEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewEnterpriseJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createNewEnterpriseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 210, 50));

        createNewEnterpriseAdminJButton.setBackground(new java.awt.Color(231, 244, 255));
        createNewEnterpriseAdminJButton.setFont(new java.awt.Font("Sathu", 0, 12)); // NOI18N
        createNewEnterpriseAdminJButton.setText("Create New Enterprise Admin");
        createNewEnterpriseAdminJButton.setMaximumSize(new java.awt.Dimension(131, 23));
        createNewEnterpriseAdminJButton.setMinimumSize(new java.awt.Dimension(131, 23));
        createNewEnterpriseAdminJButton.setPreferredSize(new java.awt.Dimension(136, 23));
        createNewEnterpriseAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewEnterpriseAdminJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createNewEnterpriseAdminJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 210, 50));

        jLabel2.setFont(new java.awt.Font("Sathu", 1, 14)); // NOI18N
        jLabel2.setText("Hello Admin, What’s your focus today? ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createNewEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewEnterpriseJButtonActionPerformed

        CreateNewEnterpriseJPanel CreateNewEnterpriseJPanel =new CreateNewEnterpriseJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("CreateNewEnterpriseJPanel",CreateNewEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);   // TODO add your handling code here:
    }//GEN-LAST:event_createNewEnterpriseJButtonActionPerformed

    private void createNewEnterpriseAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewEnterpriseAdminJButtonActionPerformed
        CreateNewEnterpriseAdminJPanel CreateNewEnterpriseAdminJPanel=new CreateNewEnterpriseAdminJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("CreateNewEnterpriseAdminJPanel",CreateNewEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_createNewEnterpriseAdminJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewEnterpriseAdminJButton;
    private javax.swing.JButton createNewEnterpriseJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
