/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TeacherRole;

import Business.EcoSystem;
import Business.Role.TeacherRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AppointmentRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geetika
 */
public class TeacherWorkAreaJPanel extends javax.swing.JPanel {

    private UserAccount currentTeacher;

public TeacherWorkAreaJPanel(UserAccount currentTeacher) {
    initComponents();
    this.currentTeacher = currentTeacher;

    // Ensure the role is a teacher
    if (!(currentTeacher.getRole() instanceof TeacherRole)) {
        throw new IllegalArgumentException("User is not a teacher");
    }

    populateAppointmentRequestsTable();
}

    private void populateAppointmentRequestsTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing rows

    // Get the global WorkQueue
    WorkQueue workQueue = EcoSystem.getInstance().getWorkQueue();

    // Filter requests for the logged-in teacher
    for (WorkRequest request : workQueue.getWorkRequestList()) {
        if (request instanceof AppointmentRequest) {
            AppointmentRequest appointmentRequest = (AppointmentRequest) request;
            if (appointmentRequest.getTeacher().equals(currentTeacher)) {
                Object[] row = new Object[4];
                row[0] = appointmentRequest.getId(); // Request ID
                row[1] = appointmentRequest.getStudent().getEmployee().getName(); // Student Name
                row[2] = appointmentRequest.getRequestDate(); // Request Date
                row[3] = appointmentRequest.getStatus(); // Status
                model.addRow(row);
            }
        }
    }
}





















    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(230, 238, 240));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teacher Sessions ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request ID", "Student Name", "Request Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
