/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DonorRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundRequest;
import Business.WorkQueue.WorkRequest;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author keerthiareddy
 */
public class FundRequestsScreenJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount donorAccount;

    /**
     * Creates new form FundRequestsJPanel
     */
    public FundRequestsScreenJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount donorAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.donorAccount = donorAccount;

        populateFundRequestsTable();
    }

    public void populateFundRequestsTable() {
     DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);

    List<WorkRequest> workRequests = system.getWorkQueue().getWorkRequestList();
    for (WorkRequest request : workRequests) {
        if (request instanceof FundRequest) {
            FundRequest fundRequest = (FundRequest) request;
            Object[] row = new Object[6];
            row[0] = fundRequest.getId();
            row[1] = fundRequest.getType();
            row[2] = fundRequest.getRequester().getEmployee().getName();
            row[3] = fundRequest.getPrice();
            row[4] = fundRequest.getAmountFunded();
            row[5] = fundRequest.getStatus();
            model.addRow(row);
        }
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel1.setText("View Fund Requests");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Request Type", "Beneficiary Name", "Amount Needed", "Amount Funded", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("<<< back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fund Requests");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // the row selected on the table's information is displayed in the text fields of the Jpanel called FundRequestsDialogJPanel 
        // if no row is selected, a message is displayed to the user to select a row
        // if a row is selected, the user is taken to the FundRequestsDialogJPanel to view the details of the request

        int selectedRow = jTable2.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a row to view details!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Get the selected FundRequest
    int requestId = (int) jTable2.getValueAt(selectedRow, 0); // ID column
    FundRequest fundRequest = (FundRequest) system.getWorkQueue().getWorkRequestById(requestId);

    if (fundRequest == null) {
        JOptionPane.showMessageDialog(this, "Unable to find the selected request. Please refresh and try again.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Navigate to FundRequestsDialogJPanel
    FundRequestsDialogJPanel panel = new FundRequestsDialogJPanel(userProcessContainer, system, donorAccount, fundRequest);
    userProcessContainer.add("FundRequestsDialogJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);














    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Navigate to the Fund Requests screen (example logic)
        userProcessContainer.remove(this);

        // Refresh the donor dashboard
        Component[] components = userProcessContainer.getComponents();
        for (Component component : components) {
            if (component instanceof DonorDashboardJPanel) {
                DonorDashboardJPanel donorDashboard = (DonorDashboardJPanel) component;
                donorDashboard.populateDashboard(); // Refresh the donor dashboard
            }
        }

        // Switch back to the donor dashboard panel
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
