/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StudentRole;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import Business.EcoSystem;
import Business.EmailUtil;
import Business.Role.StudentRole;
import Business.Role.ParentRole;
import Business.UserAccount.UserAccount;
import ui.MainJFrame;

/**
 *
 * @author harshithachennareddy
 */
public class NewStudentLoginJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form NewStudentLoginJPanel
     */
    public NewStudentLoginJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        agetxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        currentOrganisationtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        parentemailtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        locationtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        highesteducationtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        usernametxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        signupBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 230, 239));

        jLabel1.setFont(new java.awt.Font("Sathu", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" EduLink");

        jLabel2.setFont(new java.awt.Font("Sathu", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create an account and unlock your path to knowledge and opportunity!");

        jLayeredPane1.setBackground(new java.awt.Color(240, 230, 239));

        agetxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("LOCATION");

        currentOrganisationtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        emailtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        parentemailtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CURRENT ORGANISATION");

        locationtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel9.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("PASSWORD");

        jLabel7.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("AGE");

        jLabel8.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("EMAIL");

        highesteducationtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel10.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("PARENT EMAIL");

        jLabel4.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("HIGHEST EDUCATION");

        jLabel3.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NAME   ");

        nametxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        passwordtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel11.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        jLabel11.setText("USERNAME");

        jLayeredPane1.setLayer(agetxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(currentOrganisationtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(emailtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(parentemailtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(locationtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(highesteducationtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(nametxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(passwordtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(usernametxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentOrganisationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highesteducationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentemailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel6, jLabel8, jLabel9});

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agetxt, currentOrganisationtxt, emailtxt, highesteducationtxt, locationtxt, nametxt, parentemailtxt, passwordtxt});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(highesteducationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(currentOrganisationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(parentemailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agetxt, currentOrganisationtxt, emailtxt, highesteducationtxt, locationtxt, nametxt, parentemailtxt, passwordtxt});

        signupBtn.setBackground(new java.awt.Color(239, 240, 244));
        signupBtn.setFont(new java.awt.Font("Sathu", 0, 13)); // NOI18N
        signupBtn.setText("SIGN UP");
        signupBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, java.awt.Color.black, java.awt.Color.white));
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(543, 543, 543)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
       int age;
       // TODO add your handling code here:
       String name = nametxt.getText();
       String highestEducation = highesteducationtxt.getText();
       String currentOrganisation = currentOrganisationtxt.getText();
       String location = locationtxt.getText();
       
       String email = emailtxt.getText();
       String parentEmail = parentemailtxt.getText();
       String username = usernametxt.getText();
       String password = new String(passwordtxt.getPassword());

       // Check if the username is unique
       if (system.getUserAccountDirectory().getUserAccountList().stream()
           .anyMatch(account -> account.getUsername().equals(username))) {
       JOptionPane.showMessageDialog(this, "Username already exists. Please choose another.", "Error", JOptionPane.ERROR_MESSAGE);
       return;
       }

       // validate the input fields, if age is less than 18 then parent email is mandatory and except highest education and current organisation all other fields are mandatory

       if (name.isEmpty() || location.isEmpty() || email.isEmpty() || username.isEmpty() || password.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Please fill in all the mandatory fields.", "Error", JOptionPane.ERROR_MESSAGE);
           return;
       }

       // validate email format
       if (!email.contains("@") || !email.contains(".")) {
           JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Error", JOptionPane.ERROR_MESSAGE);
           return;
       }

       
       try {
           age = Integer.parseInt(agetxt.getText());
           if (age < 18 && (parentEmail.isEmpty() || !parentEmail.contains("@") || !parentEmail.contains("."))) {
               JOptionPane.showMessageDialog(this, "Please enter a valid parent email, as the student is under 18.", "Error", JOptionPane.ERROR_MESSAGE);
               return;
           }
       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "Please enter a valid age.", "Error", JOptionPane.ERROR_MESSAGE);
           return;
       }

       // Create a new UserAccount
       UserAccount newStudentAccount = new UserAccount(username, password, new StudentRole(),name, highestEducation, currentOrganisation, location, age, email, parentEmail);

       // Add the new account to the UserAccountDirectory
       system.getUserAccountDirectory().addUserAccount(newStudentAccount);

       // Send email to student and parent
       String subject = "Welcome to EduLink";
       String body = "Dear " + name + ",\n\nYour account has been successfully created on EduLink.\nUsername: " + username + "\n\nBest Regards,\nEduLink Team";
       EmailUtil.sendEmail(email, subject, body);
       if (!parentEmail.isEmpty()) {
           EmailUtil.sendEmail(parentEmail, subject, "Dear Parent,\n\nAn account has been created for " + name + " on EduLink.\n\nBest Regards,\nEduLink Team");
       }   

       // Show success message
       JOptionPane.showMessageDialog(this, "Account created successfully! You can now log in.", "Success", JOptionPane.INFORMATION_MESSAGE);

       // print the user directory

       for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {
           System.out.println(ua.getUsername());
       }

       // Clear the form fields
       nametxt.setText("");
       highesteducationtxt.setText("");
       currentOrganisationtxt.setText("");
       locationtxt.setText("");
       agetxt.setText("");
       emailtxt.setText("");
       parentemailtxt.setText("");
       usernametxt.setText("");
       passwordtxt.setText("");

       // Display a success message
       System.out.println("Student account created successfully!");

       // go to the previous screen in card layout with is just the MainJFrame
       userProcessContainer.remove(this);
       userProcessContainer.add("MainJFrame", new MainJFrame());
       ((java.awt.CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);

//           int age;
// // TODO add your handling code here:
// String name = nametxt.getText();
// String highestEducation = highesteducationtxt.getText();
// String currentOrganisation = currentOrganisationtxt.getText();
// String location = locationtxt.getText();

// String email = emailtxt.getText();
// String parentEmail = parentemailtxt.getText();
// String username = usernametxt.getText();
// String password = new String(passwordtxt.getPassword());

// // Check if the username is unique
// if (system.getUserAccountDirectory().getUserAccountList().stream()
//     .anyMatch(account -> account.getUsername().equals(username))) {
//     JOptionPane.showMessageDialog(this, "Username already exists. Please choose another.", "Error", JOptionPane.ERROR_MESSAGE);
//     return;
// }

// // Validate the input fields
// if (name.isEmpty() || location.isEmpty() || email.isEmpty() || username.isEmpty() || password.isEmpty()) {
//     JOptionPane.showMessageDialog(this, "Please fill in all the mandatory fields.", "Error", JOptionPane.ERROR_MESSAGE);
//     return;
// }

// // Validate email format
// if (!email.contains("@") || !email.contains(".")) {
//     JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Error", JOptionPane.ERROR_MESSAGE);
//     return;
// }

// try {
//     age = Integer.parseInt(agetxt.getText());
//     if (age < 18) {
//         if (parentEmail.isEmpty() || !parentEmail.contains("@") || !parentEmail.contains(".")) {
//             JOptionPane.showMessageDialog(this, "Please enter a valid parent email, as the student is under 18.", "Error", JOptionPane.ERROR_MESSAGE);
//             return;
//         }
//         // Check if parent's email is already used as a username
//         if (system.getUserAccountDirectory().getUserAccountList().stream()
//             .anyMatch(account -> account.getUsername().equals(parentEmail))) {
//             JOptionPane.showMessageDialog(this, "Parent's email is already used as a username. Please provide another email.", "Error", JOptionPane.ERROR_MESSAGE);
//             return;
//         }
//     }
// } catch (NumberFormatException e) {
//     JOptionPane.showMessageDialog(this, "Please enter a valid age.", "Error", JOptionPane.ERROR_MESSAGE);
//     return;
// }

// // Create a new UserAccount for the student
// UserAccount newStudentAccount = new UserAccount(username, password, new StudentRole(), name, highestEducation, currentOrganisation, location, age, email, parentEmail);

// // Add the student account to the UserAccountDirectory
// system.getUserAccountDirectory().addUserAccount(newStudentAccount);

// // If the student is under 18, create a parent account
// if (age < 18) {
//     String parentPassword = username; // Parent's password is set to the student's username
//     UserAccount parentAccount = new UserAccount(parentEmail, parentPassword, new ParentRole(), "Parent of " + name, "", "", location, 0, parentEmail, "");
//     system.getUserAccountDirectory().addUserAccount(parentAccount);

//     // Send email to the parent
//     String parentSubject = "Welcome to EduLink - Parent Account Created";
//     String parentBody = "Dear Parent,\n\nAn account has been created for you on EduLink to monitor " + name + "'s activities.\nUsername: " + parentEmail + "\nPassword: " + parentPassword + "\n\nBest Regards,\nEduLink Team";
//     EmailUtil.sendEmail(parentEmail, parentSubject, parentBody);
// }

// // Send email to the student
// String subject = "Welcome to EduLink";
// String body = "Dear " + name + ",\n\nYour account has been successfully created on EduLink.\nUsername: " + username + "\n\nBest Regards,\nEduLink Team";
// EmailUtil.sendEmail(email, subject, body);

// // Show success message
// JOptionPane.showMessageDialog(this, "Account created successfully! You can now log in.", "Success", JOptionPane.INFORMATION_MESSAGE);

// // Debug: Print all usernames
// for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {
//     System.out.println(ua.getUsername());
// }

// // Clear the form fields
// nametxt.setText("");
// highesteducationtxt.setText("");
// currentOrganisationtxt.setText("");
// locationtxt.setText("");
// agetxt.setText("");
// emailtxt.setText("");
// parentemailtxt.setText("");
// usernametxt.setText("");
// passwordtxt.setText("");

// // Display a success message
// System.out.println("Student and parent accounts created successfully!");

// // Go to the previous screen in card layout (MainJFrame)
// userProcessContainer.remove(this);
// userProcessContainer.add("MainJFrame", new MainJFrame());
// ((java.awt.CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);

    }//GEN-LAST:event_signupBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agetxt;
    private javax.swing.JTextField currentOrganisationtxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField highesteducationtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField locationtxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField parentemailtxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
